/*
 ============================================================================
 Name        : EL1Nentry.c
 Author      : CAP-TEE
 Version     :
 Copyright   : CAP-TEE 2021
 Description : EL1 normal code
 Limitations : The c function library is initialised by the default compile/
 	 	 	   linker to reside in the lower section of DRAM0, which is set
 	 	 	   up as the secure memory location for EL3 in this setup. This
 	 	 	   means that any c function call from the normal world such as
 	 	 	   puts jumps to secure memory to run. This is not a realistic
 	 	 	   or secure scenario in the current set up.

 	 	 	   A heap has not yet been setup
 ============================================================================
 */

//need to put into non secure memory region
#define LOCATE_FUNC  __attribute__((__section__(".NONSECUREsection_c")))
//need to put string into a read only data section for el1, away from el3 secure section
const char teststring[27] __attribute__((__section__(".el1_rodata"))) = {"abcdefghijklmnopqrstuvwxyz"};

#include <stdio.h>
#include <stdlib.h>
int testfunc(void);

int LOCATE_FUNC el1nmain(void) {

	//Morello - puts function
	// The puts c function is stored in EL3 memory space in this example,
	// will not work if the el1 mmu does not include this section of memory.
	//Morello-purecap - puts function
	// The compiler builds a capability table,
	// the puts function is located at 80003EE0
	// A local capability is created before the function call to puts,
	// c16 = 80003EE1, with LSB set to 1, this is valid
	// the PCC points to 80003EE0,
	// Note: bit[26] (c64 bit) must be set on SPSR_EL3 on an ERET to EL1
	// otherwise the tag bit on the capability and PCC gets cleared causing
	// a terminate by exception, ESR_EL1 reports with capability tag fault
	puts("now in EL1 normal");

	//Morello - .rodata string
	// this string is automatically stored in read only data section .rodata
	// string stored in .rodata section so will not work if the el1 mmu does not include this section of memory
	//Morello-purecap - .rodata string
	// The capability pointer is stored at 800080d0 (depending what else is compiled in this example)
	// The actual string is stored at 8000000B (depending what else is compiled in this example)
	// The capability is loaded into a capability register and points at the string location
	char *teststr1 = "Hello World from EL1N\n";

	puts("done testsrtr1");

	//Morello - .el1_rodata string
	// this string is stored in .el1_rodata section now
	// and placed in a location defined by the linker script
	// can be a long string
	// should work with mmu, since the string should be stored in el1n memory space defined by linker
	//Morello-purecap - .el1_rodata string
	// The capability pointer to the string is stored in the capability table generated by the compiler
	// start c0 8000 81b0, end c1 8000 B130
	// and copied to 800080xx during (.Init_global_caps) in _start code
	// the capability is then loaded, and stored locally when this code runs
	// To allow this to work with mmu at el1, this area of memory 800080xx needs to be read only
	// or each el program needs to be compiled as separate images to confine capabilities into desired area
	const char *teststr2 = teststring;

	puts("done testsrtr2");

	//local string created in code section, must be short string
	//Works with Morello and Morello-purecap
	char teststr3[8] = {'E', 'L', '1', 'N', '\n', '\0'};

	puts("done testsrtr3");

	//Morello - testfunc
	// test function calls, to test stack alignment
	//Morello-purecap - testfunc
    // Note: bit[26] (c64 bit) must be set on SPSR_EL3 on an ERET to EL1
	// otherwise the tag bit gets cleared and terminates by exception
	testfunc();

	puts("done testfunc");

	//wait here
	//Works for both Morello, and Morello-purecap
	volatile uint32_t flag = 1;
	while(flag==1){}

	// We never get here
	return EXIT_SUCCESS;
}

int LOCATE_FUNC testfunc(void){
	char teststr4[8] = {'E', 'L', '1', 'N', '\n', '\0'};
	return 0;
}
