/*
 ============================================================================
 Name        : exceptionHandlerFuncsEL1S.c
 Author      : CAP-TEE
 Version     :
 Copyright   : CAP-TEE 2021
 Description : EL1S exception handler functions
   	 	 	   Contains a FIQ exception handler for secure group 0
 	 	 	   generated by EL1S in program state 1
 ============================================================================
 */

//*****************************************
// INCLUDES
//*****************************************
#include <stdio.h>
#include <stdlib.h>

// Program defined headers
#include "uartS.h"
#include "exceptionHandlerFuncsEL1S.h" //include the global flagEL1S flag

//functions used
extern void stopTimerS(void);
extern uint32_t getIntidAckReg0S(void);
extern void setIntidEndReg0S(uint32_t);

//*****************************************
// FUNCTIONS
//*****************************************
//------------------------------------
// fiqHandlerEL1S
//------------------------------------
// FIQ exception handler for EL1S, program state 1
// This is called by the vector table
// checks for the secure physical timer event
// disables the timer and resets the interrupt
// Note: this example uses secure group 0 (FIQ) for secure EL1
void fiqHandlerEL1S(void)
{
uint32_t intid;
// get group 0 interrupt id from acknowledge register
intid = getIntidAckReg0S();
// uartSTransmitString("inside fiqHandlerEL1S\n");
// Secure and non-secure timer events have different interrupt IDs
//   ID30 = Non-secure Physical Timer Event.
//   ID29 = Secure Physical Timer Event
if (intid == 29)
{
	// uartSTransmitString("ID is 29\n"); //must be 29 if here
	flagEL1S = 1;
	// stop secure timer
	stopTimerS();
}
else
{
	// error
}
// set end of interrupt for ID 29 - group 0 register
setIntidEndReg0S(intid);
return;
}
