/*
 ============================================================================
 Name        : exceptionHandlerFuncsEL1N.c
 Author      : CAP-TEE
 Version     :
 Copyright   : CAP-TEE 2021
 Description : EL1N exception handler functions
 	 	 	   Contains an IRQ exception handler for non secure group 1
 	 	 	   generated by EL1N in program state 1
 ============================================================================
 */

//*************************************************
// DEFINES
//*************************************************
// define attributes for non secure memory sections
// this is used by the linker script to place non secure program code into non secure memory
// attributes can be assigned to functions and global variables
#define HANDLER_FUNC  __attribute__((__section__(".NONSECUREhandlerFuncSection_c")))

//*************************************************
// INCLUDES
//*************************************************
#include <stdio.h>
#include <stdlib.h>

// Program defined headers
#include "uartN.h" 						// uart non secure functions
#include "exceptionHandlerFuncsEL1N.h"  // include the global flagEL1N flag

// timer functions
extern void disableTimerN(void);    	// timerN.s
// group 1 interrupt functions
extern uint32_t readIAR1N(void);		// gicN.s
extern void writeEOIR1N(uint32_t);		// gicN.s


//************************************
// FUNCTIONS
//************************************
//------------------------------------
// irqHandlerEL1N
//------------------------------------
// IRQ exception handler for EL1, program state 1
// This is called by the vector table
// checks for the non secure physical timer event
// disables the timer and resets the interrupt
// Note: this example uses Non-secure group 1 (IRQ) for Non secure EL1
void HANDLER_FUNC irqHandlerEL1N(void)
{
	uint32_t intid;
	// read group 1 interrupt acknowledge register
	intid = readIAR1N();
	// local string - don't forget the \n else will get overwritten by next message
	char uartstr[8] = {'I', 'R', 'Q', ' ', 'N', '\n', '\0'};
	char uartstr1[7] = {'I', 'D', '3', '0', '\n', '\0'};
	// uartNTransmitString(uartstr);
	// Secure and non-secure timer events have different interrupt IDs
	//   ID30 = Non secure Physical Timer Event.
	//   ID29 = Secure Physical Timer Event
	if (intid == 30)
	{
		// uartNTransmitString(uartstr1); //ID must be 30
		// set global EL1N flag so EL1N knows got the interrupt
		flagEL1N = 1;
		// disable the non secure physical timer
		disableTimerN();
	} else {
		// Should never get here
	}
	// write end of interrupt for ID 30 - group 1 register
	writeEOIR1N(intid);
	return;
}
