/*
 ============================================================================
 Name        : exceptionHandlerFuncsEL1S.h
 Author      : CAP-TEE
 Version     :
 Copyright   : CAP-TEE 2021
 Description : EL1S exception handler functions
  	 	 	   Contains a FIQ exception handler for secure group 0
 	 	 	   generated by EL1S in program state 1
 ============================================================================
 */
#ifndef __exceptionHandlerFuncsEL1S_h
#define __exceptionHandlerFuncsEL1S_h

void fiqHandlerEL1S(void);

#endif
