/*
 ============================================================================
 Name        : exceptionHandlerFuncsEL3.c
 Author      : CAP-TEE
 Version     :
 Copyright   : CAP-TEE 2021
 Description : EL3 exception handler functions
 	 	 	   Contains a FIQ exception handler for secure group 0
 	 	 	   generated by EL3
 ============================================================================
 */

#include <stdio.h>
#include <stdlib.h>
#include "exceptionHandlerFuncsEL3.h" //include the global flagEL3 flag

//functions used
extern void stopTimerS(void);
extern uint32_t getIntidAckReg0S(void);
extern void setIntidEndReg0S(uint32_t);

// get global flag
extern volatile uint32_t flagEL3;

//************************************
//fiqHandlerEL3
//************************************
//FIQ exception handler for EL3
//This is called by the vector table
//checks for the secure physical timer event
//disables the timer and resets the interrupt
//Note: this example uses secure group 0 (FIQ) for secure EL3
void fiqHandlerEL3(void)
{
uint32_t intid;
//get group 0 interrupt id from acknowledge register
intid = getIntidAckReg0S();
puts("inside fiqHandlerEL3");
// Secure and non-secure timer events have different interrupt IDs
//   ID30 = Non-secure Physical Timer Event.
//   ID29 = Secure Physical Timer Event
if (intid == 29)
{
	puts("ID is 29"); //must be 29 if here
	flagEL3 = 1;
	stopTimerS();
}
else
{
	//error
}
//set end of interrupt for ID 29 - group 0 register
setIntidEndReg0S(intid);
return;
}
